# Generated by Django 4.0.5 on 2022-06-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_rename_createdby_exercise_ownder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='ownder',
            new_name='owner',
        ),
    ]
