# Generated by Django 4.0.5 on 2022-06-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_rename_ownder_exercise_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
