# Generated by Django 4.0.5 on 2022-06-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_rename_owner_id_exercise_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='grouping',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
