# Generated by Django 4.0.5 on 2022-06-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_alter_exercise_grouping_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='grouping',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
    ]
