# Generated by Django 4.0.5 on 2022-06-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_note', '0002_note_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='month',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
